### ISSUE TITLE
Binaural Simulator cannot be created, when config is in a different folder

### ISSUE THREAD

**Issue by dennisguse** [TWOEARS/TwoEars#2] opened 2015-09-21 13:31 UTC
Trying to create simulator, when the config file is not in the _current_ folder.

Let XXXX be the name of the folder

```
simulator.SimulatorConvexRoom('XXXX/binaural_renderer.xml');
```

Results in a re-download (although download was already done) and in addition, download fails.

Version: 1.0.1 RELEASE

**Comment by hagenw** [comment] 2016-09-27 20:43
@fietew: is this still a problem?

**Comment by fietew** [comment] 2016-09-28 09:27
In the current master of TWOEARS/binaural-simulator, i can call 

```
simulator.SimulatorConvexRoom('test/test_binaural.xml')
```

from the root directory of the repository.

**Comment by hagenw** [comment] 2016-09-28 09:38
Looking at the responsible code I can also find no reason why it should not work at the moment.
As long as we are not able to reproduce this again I will close this bug.

**Closed as completed by hagenw** 2016-09-28 09:38 UTC
